name: mighty_radio
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #BASE
  cupertino_icons: ^1.0.4
  google_fonts: ^2.3.2
  intl: ^0.17.0

  #UI
  cached_network_image: ^3.2.0
  flutter_staggered_animations: 1.0.0
  flutter_vector_icons: ^1.0.0
  lottie: ^1.3.0

  #STATE MANAGEMENT
  mobx: ^2.0.7
  flutter_mobx: ^2.0.5

  #CONNECTIVITY
  http: ^0.13.4
  connectivity_plus: ^2.3.0
  package_info_plus: ^1.4.2
  share_plus: ^4.0.4
  store_redirect: ^2.0.1

  # WEB TOOLS
  flutter_inappwebview: ^5.4.2

  # ADS
  google_mobile_ads: ^1.2.0
  facebook_audience_network: ^1.0.1

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.3.0

  # LAUNCH URL
  url_launcher: ^6.1.0

  #Database
  shared_preferences: ^2.0.13

  #Audio
  assets_audio_player: ^3.0.4+1

  # Other
  fluttertoast: ^8.0.9
  html: ^0.15.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.6
  build_runner: ^2.1.10
  #flutter packages pub run build_runner build --delete-conflicting-outputs

  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/ca/
